services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: retro2mqtt_mosquitto
    networks:
      - retro
    ports:
      - "1883:1883"
    volumes:
      - ./.mosquitto/config:/mosquitto/config
    restart: unless-stopped

  homeassistant:
    image: homeassistant/home-assistant
    container_name: retro2mqtt_homeassistant
    networks:
      - retro
    ports:
      - "8123:8123"
    volumes:
      - ./.homeassistant/config:/config
    environment:
      - TZ=Norway/Oslo
    restart: unless-stopped

networks:
  retro:
    driver: bridge
