services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    networks:
      - retro
    ports:
      - "1883:1883"
    volumes:
      - ./.mosquitto/config:/mosquitto/config
    restart: unless-stopped

  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    networks:
      - retro
    ports:
      - "8123:8123"
    volumes:
      - ./.homeassistant/config:/config
    environment:
      - TZ=Norway/Oslo
    restart: unless-stopped

networks:
  retro:
    driver: bridge

#  retro2mqtt:
#    build: .
#    container_name: retro2mqtt
#    network_mode: host
#    volumes:
#      - ./config.edn:/app/config.edn
#      - ~/.config/retroarch/logs:/app/retroarch/logs:ro
#    environment:
#      - CONFIG_FILE=config.edn
#    restart: unless-stopped
#    depends_on:
#      - mosquitto
